from __future__ import annotations

from datetime import date

REFERENCE_DATE = date(2026, 6, 1)

PREFERRED_CITIES = {
    "pune", "noida", "delhi", "gurgaon", "gurugram", "mumbai", "hyderabad"
}

CONSULTING_COMPANIES = {
    "tcs", "tata consultancy services", "infosys", "wipro", "accenture",
    "cognizant", "capgemini", "hcl", "hcl technologies", "tech mahindra",
    "mindtree", "ltimindtree", "mphasis", "genpact"
}

RELEVANT_TITLE_TERMS = (
    "machine learning",
    "ml engineer",
    "ai engineer",
    "applied scientist",
    "applied ml",
    "data scientist",
    "nlp engineer",
    "search engineer",
    "recommendation systems engineer",
    "relevance engineer",
    "ranking engineer",
    "matching engineer",
    "personalization engineer",
    "retrieval engineer",
    "recommendation",
    "ranking",
    "retrieval",
)

# These are grouped by the requirement they prove. Career-history matches carry
# much more weight than profile-summary or skill-list matches.
PATTERN_GROUPS: dict[str, tuple[str, ...]] = {
    "ranking": (
        "ranking",
        "ranker",
        "learning-to-rank",
        "learning to rank",
        "re-ranking",
        "reranking",
        "re-rank",
        "relevance ranking",
        "relevance",
        "scoring function",
        "discovery feed",
        "recommendation system",
        "recommendation-style",
        "personalization",
        "match quality",
        "candidate ranking",
        "candidate ranking system",
    ),
    "retrieval": (
        "retrieval",
        "semantic search",
        "hybrid search",
        "dense retrieval",
        "sparse and dense",
        "bm25",
        "embedding-based search",
        "embedding ranker",
        "vector search",
        "candidate-jd matching",
        "matching layer",
        "query understanding",
        "surface relevant",
        "search and discovery",
        "information retrieval",
        "match people to roles",
        "most relevant matches",
        "connect them to the most relevant",
    ),
    "vector_infra": (
        "faiss",
        "pinecone",
        "qdrant",
        "milvus",
        "weaviate",
        "opensearch",
        "elasticsearch",
        "hnsw",
        "vector database",
        "vector index",
        "index refresh",
        "index versioning",
        "embedding versioning",
        "nearest-neighbor",
        "ann index",
        "embedding store",
    ),
    "evaluation": (
        "ndcg",
        "mrr",
        "map",
        "recall@",
        "offline-online",
        "offline online",
        "offline metrics",
        "online metrics",
        "a/b test",
        "a/b testing",
        "ab test",
        "human relevance",
        "human judgments",
        "relevance labeling",
        "eval framework",
        "evaluation framework",
        "feedback loop",
        "metric correlation",
        "offline experimentation",
        "online experimentation",
        "human relevance judgments",
        "interleaving",
    ),
    "production": (
        "production",
        "shipped",
        "deployed",
        "serving",
        "served",
        "rollout",
        "real users",
        "queries per month",
        "million users",
        "millions of users",
        "millions of queries",
        "billion",
        "at scale",
        "p95",
        "latency",
        "migration",
        "migrated",
        "operated",
        "production traffic",
        "user-facing",
    ),
    "ownership": (
        "owned",
        "led",
        "designed",
        "built",
        "drove",
        "architected",
        "end-to-end",
        "end to end",
        "from scratch",
        "mentored",
        "team of",
        "across the rollout",
        "principal owner",
        "hands-on owner",
    ),
    "role_depth": (
        "staff",
        "principal",
        "lead",
        "senior",
        "head",
        "director",
        "from scratch",
        "mentored",
    ),
    "python": (
        "python",
        "pytorch",
        "scikit-learn",
        "sklearn",
        "fastapi",
        "flask",
        "xgboost",
        "lightgbm",
        "sentence-transformers",
        "hugging face",
        "pandas",
        "numpy",
    ),
    "fine_tuning": (
        "lora",
        "qlora",
        "peft",
        "fine-tuned",
        "fine tuned",
        "fine-tuning",
    ),
    "scale_systems": (
        "kubernetes",
        "kubeflow",
        "mlflow",
        "feature store",
        "distributed",
        "batching",
        "quantiz",
        "monitoring",
        "drift",
        "retraining",
        "rollback",
        "online serving",
        "experimentation platform",
    ),
}

EVIDENCE_LEVELS = {
    0: "skill-list mention only",
    1: "summary/headline claim",
    2: "career-description usage",
    3: "production ownership with scale/metric",
    4: "end-to-end ownership plus evaluation/experimentation",
}

NEGATIVE_PATTERNS: dict[str, tuple[str, ...]] = {
    "recent_llm_only": (
        "recently started learning langchain",
        "building small rag demos",
        "calling openai",
        "experimented with chatgpt",
        "ai-assisted content",
        "prompt engineer",
    ),
    "cv_speech_only": (
        "computer vision models",
        "image moderation",
        "image classification",
        "object detection",
        "speech recognition",
        "robotics",
    ),
    "research_only": (
        "academic lab",
        "pure research",
        "research-only",
        "research only",
        "university",
        "phd",
    ),
}
